"""
Seed script — 66 hairstyle catalog entries (42 male + 24 female).

Sources:
  Male   — moderngentlemanmagazine.com/42-best-men-over-60-haircuts/
  Female — therighthairstyles.com/30-best-hairstyles-and-haircuts-for-women-over-60-to-suit-any-taste/

Run via: python -m app.db.seeds.hairstyle_seed
"""
from __future__ import annotations

import asyncio
import uuid

from sqlalchemy import delete, func, select

from app.db.engine import AsyncSessionFactory
from app.db.models import HairstyleCatalog

CATALOG: list[dict] = [
    # ─────────────────────────────────────────────────────────────────────────
    # MALE — short
    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Timeless Taper Fade",
        "slug": "timeless-taper-fade",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.92, "compat_round": 0.75, "compat_square": 0.88,
        "compat_heart": 0.80, "compat_oblong": 0.70, "compat_diamond": 0.85,
        "barber_notes": "Low skin fade on sides, blend to natural hair on top. Scissor-finish top to 3 cm.",
        "barber_guard": "#1 skin–#3 blend",
        "top_length_cm": 3.0,
        "preview_s3_key": "male/timeless-taper-fade.jpeg",
    },
    {
        "name": "Classic Crew Cut",
        "slug": "classic-crew-cut",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.80, "compat_square": 0.85,
        "compat_heart": 0.78, "compat_oblong": 0.70, "compat_diamond": 0.80,
        "barber_notes": "Taper sides with #2, blend into top. Scissor-finish top to 2 cm. Clean neckline.",
        "barber_guard": "#2 sides / #4 top",
        "top_length_cm": 2.0,
        "preview_s3_key": "male/classic-crew-cut.jpeg",
    },
    {
        "name": "Short Caesar Cut",
        "slug": "short-caesar-cut",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.90, "compat_square": 0.80,
        "compat_heart": 0.72, "compat_oblong": 0.78, "compat_diamond": 0.75,
        "barber_notes": "Horizontal fringe 2–3 cm, uniform top 3 cm, taper sides #2.",
        "barber_guard": "#2 sides",
        "top_length_cm": 3.0,
        "preview_s3_key": "male/short-caesar-cut.jpeg",
    },
    {
        "name": "Buzz Cut",
        "slug": "buzz-cut",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.95, "compat_round": 0.62, "compat_square": 0.80,
        "compat_heart": 0.68, "compat_oblong": 0.55, "compat_diamond": 0.72,
        "barber_notes": "Uniform #2 all over. Clean neckline and temples.",
        "barber_guard": "#2 all over",
        "top_length_cm": 0.6,
        "preview_s3_key": "male/buzz-cut.jpeg",
    },
    {
        "name": "Buzz Fade",
        "slug": "buzz-fade",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.92, "compat_round": 0.70, "compat_square": 0.88,
        "compat_heart": 0.75, "compat_oblong": 0.65, "compat_diamond": 0.85,
        "barber_notes": "Skin fade on sides up to occipital bone. Buzz top #3 uniform.",
        "barber_guard": "Skin–#2 fade / #3 top",
        "top_length_cm": 0.9,
        "preview_s3_key": "male/buzz-fade.jpeg",
    },
    {
        "name": "Buzz Cut with a Twist",
        "slug": "buzz-cut-with-a-twist",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.92, "compat_round": 0.68, "compat_square": 0.82,
        "compat_heart": 0.70, "compat_oblong": 0.60, "compat_diamond": 0.75,
        "barber_notes": "Standard buzz with a design line or part shaved in at temple.",
        "barber_guard": "#1–#2 all over",
        "top_length_cm": 0.6,
        "preview_s3_key": "male/buzz-cut-with-a-twist.jpeg",
    },
    {
        "name": "Military Buzz Cut",
        "slug": "military-buzz-cut",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.65, "compat_square": 0.85,
        "compat_heart": 0.68, "compat_oblong": 0.58, "compat_diamond": 0.72,
        "barber_notes": "Induction-style, #1 uniform or shorter. Very sharp fade at temples.",
        "barber_guard": "#1 all over",
        "top_length_cm": 0.3,
        "preview_s3_key": "male/military-buzz-cut.jpeg",
    },
    {
        "name": "Ivy League Cut",
        "slug": "ivy-league-cut",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.75, "compat_square": 0.82,
        "compat_heart": 0.88, "compat_oblong": 0.75, "compat_diamond": 0.82,
        "barber_notes": "Side-part, taper sides #3, scissor top to 4 cm, blend part line.",
        "barber_guard": "#3 sides",
        "top_length_cm": 4.0,
        "preview_s3_key": "male/ivy-league-cut.jpeg",
    },
    {
        "name": "Flat Top",
        "slug": "flat-top",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.85, "compat_round": 0.72, "compat_square": 0.80,
        "compat_heart": 0.70, "compat_oblong": 0.88, "compat_diamond": 0.82,
        "barber_notes": "Level top using comb-and-clippers technique. Skin-fade sides for contrast.",
        "barber_guard": "Skin sides / flat comb top",
        "top_length_cm": 5.0,
        "preview_s3_key": "male/flat-top.jpeg",
    },
    {
        "name": "Bald Fade",
        "slug": "bald-fade",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.72, "compat_square": 0.85,
        "compat_heart": 0.70, "compat_oblong": 0.62, "compat_diamond": 0.80,
        "barber_notes": "Skin fade from ear down. Medium on top (#4–#5). Sharp line-up.",
        "barber_guard": "Skin–#4 fade",
        "top_length_cm": 2.0,
        "preview_s3_key": "male/bald-fade.jpeg",
    },
    {
        "name": "High and Tight",
        "slug": "high-and-tight",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.72, "compat_square": 0.88,
        "compat_heart": 0.70, "compat_oblong": 0.65, "compat_diamond": 0.82,
        "barber_notes": "Skin fade high on sides, leave flat #3–#4 on top. Very little blending.",
        "barber_guard": "Skin sides / #3 top",
        "top_length_cm": 1.0,
        "preview_s3_key": "male/high-and-tight.jpeg",
    },
    {
        "name": "French Crop",
        "slug": "french-crop",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.85, "compat_square": 0.78,
        "compat_heart": 0.75, "compat_oblong": 0.78, "compat_diamond": 0.78,
        "barber_notes": "Textured fringe forward, short on sides with skin or low fade. Top 4–5 cm.",
        "barber_guard": "#2 sides",
        "top_length_cm": 4.5,
        "preview_s3_key": "male/french-crop.jpeg",
    },
    {
        "name": "Angular Cut",
        "slug": "angular-cut",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.85, "compat_round": 0.68, "compat_square": 0.88,
        "compat_heart": 0.72, "compat_oblong": 0.78, "compat_diamond": 0.82,
        "barber_notes": "Hard geometric lines at temples. Disconnected undercut. Sharp edges.",
        "barber_guard": "#0 sides / 5–6 cm top",
        "top_length_cm": 5.5,
        "preview_s3_key": "male/angular-cut.jpeg",
    },
    {
        "name": "Classic Bald Head",
        "slug": "classic-bald-head",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.65, "compat_square": 0.80,
        "compat_heart": 0.72, "compat_oblong": 0.60, "compat_diamond": 0.75,
        "barber_notes": "Full head shave with straight razor. Moisturise scalp daily. Touch up every 3–4 days.",
        "barber_guard": "Razor / 0 guard",
        "top_length_cm": 0.0,
        "preview_s3_key": "male/classic-bald-head.jpeg",
    },
    {
        "name": "Clean Shaven Bald",
        "slug": "clean-shaven-bald",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.65, "compat_square": 0.80,
        "compat_heart": 0.70, "compat_oblong": 0.60, "compat_diamond": 0.75,
        "barber_notes": "Weekly razor shave. Use SPF 50 on scalp daily. Exfoliate twice weekly.",
        "barber_guard": "Straight razor",
        "top_length_cm": 0.0,
        "preview_s3_key": "male/clean-shaven-bald.jpeg",
    },
    {
        "name": "Textured Crop",
        "slug": "textured-crop",
        "gender": "male", "texture": "wavy", "length": "short", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.82, "compat_square": 0.78,
        "compat_heart": 0.80, "compat_oblong": 0.72, "compat_diamond": 0.82,
        "barber_notes": "Taper sides #3, textured top 4 cm with thinning shears, messy fringe forward.",
        "barber_guard": "#3 sides",
        "top_length_cm": 4.0,
        "preview_s3_key": "male/textured-crop.jpeg",
    },
    {
        "name": "Choppy Textured Crop",
        "slug": "choppy-textured-crop",
        "gender": "male", "texture": "wavy", "length": "short", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.82, "compat_square": 0.75,
        "compat_heart": 0.80, "compat_oblong": 0.72, "compat_diamond": 0.80,
        "barber_notes": "Point-cut choppy texture on top. Low fade on sides. Sea-salt spray to finish.",
        "barber_guard": "#2 sides",
        "top_length_cm": 5.0,
        "preview_s3_key": "male/choppy-textured-crop.jpeg",
    },
    {
        "name": "Caesar with Tapered Sides",
        "slug": "caesar-tapered-sides",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.88, "compat_square": 0.78,
        "compat_heart": 0.72, "compat_oblong": 0.78, "compat_diamond": 0.75,
        "barber_notes": "Horizontal fringe 2–3 cm, taper sides #3, uniform scissor top.",
        "barber_guard": "#3 sides",
        "top_length_cm": 3.0,
        "preview_s3_key": "male/caesar-tapered-sides.jpeg",
    },
    {
        "name": "Buzzed Pompadour",
        "slug": "buzzed-pompadour",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.68, "compat_square": 0.75,
        "compat_heart": 0.82, "compat_oblong": 0.88, "compat_diamond": 0.82,
        "barber_notes": "High skin fade, top 4–5 cm brushed back with pomade for definition.",
        "barber_guard": "Skin–#2 / 4–5 cm top",
        "top_length_cm": 5.0,
        "preview_s3_key": "male/buzzed-pompadour.jpeg",
    },
    {
        "name": "Mid Fade with Part",
        "slug": "mid-fade-with-part",
        "gender": "male", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.78, "compat_square": 0.85,
        "compat_heart": 0.80, "compat_oblong": 0.72, "compat_diamond": 0.85,
        "barber_notes": "Mid fade from temple, hard part on one side, comb over top with light hold product.",
        "barber_guard": "#1–#3 mid fade",
        "top_length_cm": 5.5,
        "preview_s3_key": "male/mid-fade-with-part.jpeg",
    },
    {
        "name": "Short Textured Waves",
        "slug": "short-textured-waves",
        "gender": "male", "texture": "wavy", "length": "short", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.78, "compat_square": 0.75,
        "compat_heart": 0.80, "compat_oblong": 0.72, "compat_diamond": 0.82,
        "barber_notes": "Low taper on sides. Leave wavy top at 4–5 cm. Curl cream to define waves.",
        "barber_guard": "#3 sides",
        "top_length_cm": 4.5,
        "preview_s3_key": "male/short-textured-waves.jpeg",
    },
    # ─────────────────────────────────────────────────────────────────────────
    # MALE — medium
    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Modern Pompadour",
        "slug": "modern-pompadour",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "high",
        "compat_oval": 0.95, "compat_round": 0.65, "compat_square": 0.72,
        "compat_heart": 0.85, "compat_oblong": 0.90, "compat_diamond": 0.80,
        "barber_notes": "High fade on sides, top 7–8 cm. Blow dry forward then back. Strong pomade finish.",
        "barber_guard": "High skin–#2 fade",
        "top_length_cm": 7.5,
        "preview_s3_key": "male/modern-pompadour.jpeg",
    },
    {
        "name": "Pompadour Fade",
        "slug": "pompadour-fade",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "high",
        "compat_oval": 0.95, "compat_round": 0.65, "compat_square": 0.70,
        "compat_heart": 0.85, "compat_oblong": 0.90, "compat_diamond": 0.80,
        "barber_notes": "Mid fade on sides, 6–7 cm swept-back top with pomade. Blow dry at root.",
        "barber_guard": "#1–#3 mid fade",
        "top_length_cm": 7.0,
        "preview_s3_key": "male/pompadour-fade.jpeg",
    },
    {
        "name": "Pompadour with Tapered Fade",
        "slug": "pompadour-tapered-fade",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "high",
        "compat_oval": 0.95, "compat_round": 0.65, "compat_square": 0.70,
        "compat_heart": 0.85, "compat_oblong": 0.92, "compat_diamond": 0.82,
        "barber_notes": "Tapered rather than hard fade. 7 cm top blow-dried back. Matte pomade finish.",
        "barber_guard": "#1–#3 taper",
        "top_length_cm": 7.0,
        "preview_s3_key": "male/pompadour-tapered-fade.jpeg",
    },
    {
        "name": "Slicked-Back Pompadour with Fade",
        "slug": "slicked-back-pompadour-fade",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "high",
        "compat_oval": 0.92, "compat_round": 0.65, "compat_square": 0.70,
        "compat_heart": 0.82, "compat_oblong": 0.90, "compat_diamond": 0.82,
        "barber_notes": "Fade sides, slick back 7 cm top with strong hold. Define with comb.",
        "barber_guard": "Skin–#2 fade",
        "top_length_cm": 7.0,
        "preview_s3_key": "male/slicked-back-pompadour-fade.jpeg",
    },
    {
        "name": "Side Parted Comb Over",
        "slug": "side-parted-comb-over",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.78, "compat_square": 0.82,
        "compat_heart": 0.85, "compat_oblong": 0.78, "compat_diamond": 0.80,
        "barber_notes": "Hard part on left, taper #3 right side. 6 cm top combed across with medium hold.",
        "barber_guard": "#3 sides",
        "top_length_cm": 6.0,
        "preview_s3_key": "male/side-parted-comb-over.jpeg",
    },
    {
        "name": "Slicked-Back Hairstyle",
        "slug": "slicked-back-hairstyle",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "high",
        "compat_oval": 0.92, "compat_round": 0.65, "compat_square": 0.75,
        "compat_heart": 0.80, "compat_oblong": 0.88, "compat_diamond": 0.82,
        "barber_notes": "Low taper on sides. 7 cm top dried backward. Water-based pomade for shine.",
        "barber_guard": "#3 sides",
        "top_length_cm": 7.0,
        "preview_s3_key": "male/slicked-back-hairstyle.jpeg",
    },
    {
        "name": "Slicked-Back Undercut",
        "slug": "slicked-back-undercut",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "high",
        "compat_oval": 0.92, "compat_round": 0.68, "compat_square": 0.75,
        "compat_heart": 0.82, "compat_oblong": 0.88, "compat_diamond": 0.85,
        "barber_notes": "Skin undercut on sides, 7–8 cm top slicked straight back with strong pomade.",
        "barber_guard": "Skin sides",
        "top_length_cm": 7.5,
        "preview_s3_key": "male/slicked-back-undercut.jpeg",
    },
    {
        "name": "Textured Quiff",
        "slug": "textured-quiff",
        "gender": "male", "texture": "wavy", "length": "medium", "maintenance": "medium",
        "compat_oval": 0.95, "compat_round": 0.68, "compat_square": 0.72,
        "compat_heart": 0.85, "compat_oblong": 0.90, "compat_diamond": 0.85,
        "barber_notes": "Fade sides to #2, scissor top 6 cm, texturize with thinning shears. Blow dry forward.",
        "barber_guard": "#2 sides",
        "top_length_cm": 6.0,
        "preview_s3_key": "male/textured-quiff.jpeg",
    },
    {
        "name": "Textured Quiff with Fade",
        "slug": "textured-quiff-fade",
        "gender": "male", "texture": "wavy", "length": "medium", "maintenance": "medium",
        "compat_oval": 0.95, "compat_round": 0.68, "compat_square": 0.72,
        "compat_heart": 0.85, "compat_oblong": 0.90, "compat_diamond": 0.85,
        "barber_notes": "Skin-to-mid fade, 6–7 cm textured quiff. Matte clay or wax for hold.",
        "barber_guard": "Skin–#2 fade",
        "top_length_cm": 6.5,
        "preview_s3_key": "male/textured-quiff-fade.jpeg",
    },
    {
        "name": "Shaggy Cut",
        "slug": "shaggy-cut",
        "gender": "male", "texture": "wavy", "length": "medium", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.75, "compat_square": 0.72,
        "compat_heart": 0.85, "compat_oblong": 0.88, "compat_diamond": 0.82,
        "barber_notes": "Layered scissor cut all over 7–8 cm. Razor-end the edges. Air dry or diffuse.",
        "top_length_cm": 8.0,
        "preview_s3_key": "male/shaggy-cut.jpeg",
    },
    {
        "name": "Side Swept Layers",
        "slug": "side-swept-layers",
        "gender": "male", "texture": "wavy", "length": "medium", "maintenance": "medium",
        "compat_oval": 0.88, "compat_round": 0.72, "compat_square": 0.75,
        "compat_heart": 0.88, "compat_oblong": 0.82, "compat_diamond": 0.85,
        "barber_notes": "Long layers 7–8 cm. Side-sweep with brush and light hold wax.",
        "top_length_cm": 8.0,
        "preview_s3_key": "male/side-swept-layers.jpeg",
    },
    {
        "name": "Curly Fade",
        "slug": "curly-fade",
        "gender": "male", "texture": "curly", "length": "medium", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.75, "compat_square": 0.72,
        "compat_heart": 0.80, "compat_oblong": 0.85, "compat_diamond": 0.88,
        "bonus_curly_hair": 0.2,
        "barber_notes": "Mid fade on sides. Leave curls on top 7–8 cm. Shape with pick, curl cream.",
        "barber_guard": "#2 to #4 mid fade",
        "top_length_cm": 8.0,
        "preview_s3_key": "male/curly-fade.jpeg",
    },
    {
        "name": "Loose Side Part",
        "slug": "loose-side-part",
        "gender": "male", "texture": "wavy", "length": "medium", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.78, "compat_square": 0.80,
        "compat_heart": 0.85, "compat_oblong": 0.78, "compat_diamond": 0.82,
        "barber_notes": "Low taper sides, 6–7 cm top parted loosely. Light cream for hold.",
        "barber_guard": "#3 sides",
        "top_length_cm": 7.0,
        "preview_s3_key": "male/loose-side-part.jpeg",
    },
    {
        "name": "Comb Over with Textured Top",
        "slug": "comb-over-textured-top",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.78, "compat_square": 0.82,
        "compat_heart": 0.85, "compat_oblong": 0.78, "compat_diamond": 0.82,
        "barber_notes": "Low fade, 6 cm comb-over top texturized with thinning shears. Medium hold clay.",
        "barber_guard": "#2 fade",
        "top_length_cm": 6.0,
        "preview_s3_key": "male/comb-over-textured-top.jpeg",
    },
    {
        "name": "Faux Hawk",
        "slug": "faux-hawk",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "medium",
        "compat_oval": 0.92, "compat_round": 0.68, "compat_square": 0.78,
        "compat_heart": 0.80, "compat_oblong": 0.88, "compat_diamond": 0.85,
        "barber_notes": "Fade sides, gather centre top 5–6 cm with firm gel or pomade into a ridge.",
        "barber_guard": "Skin–#2 sides",
        "top_length_cm": 6.0,
        "preview_s3_key": "male/faux-hawk.jpeg",
    },
    {
        "name": "Medium Length Waves",
        "slug": "medium-length-waves",
        "gender": "male", "texture": "wavy", "length": "medium", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.72, "compat_square": 0.75,
        "compat_heart": 0.82, "compat_oblong": 0.88, "compat_diamond": 0.85,
        "barber_notes": "Long layers, allow waves to fall naturally. Trim ends every 8 weeks.",
        "top_length_cm": 10.0,
        "preview_s3_key": "male/medium-length-waves.jpeg",
    },
    {
        "name": "Side Swept Ivy League",
        "slug": "side-swept-ivy-league",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.75, "compat_square": 0.80,
        "compat_heart": 0.88, "compat_oblong": 0.78, "compat_diamond": 0.82,
        "barber_notes": "Taper sides #3, longer top 5–6 cm swept to one side. Light pomade.",
        "barber_guard": "#3 sides",
        "top_length_cm": 6.0,
        "preview_s3_key": "male/side-swept-ivy-league.jpeg",
    },
    # ─────────────────────────────────────────────────────────────────────────
    # MALE — long
    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Long and Layered",
        "slug": "long-and-layered",
        "gender": "male", "texture": "wavy", "length": "long", "maintenance": "medium",
        "compat_oval": 0.88, "compat_round": 0.65, "compat_square": 0.72,
        "compat_heart": 0.82, "compat_oblong": 0.92, "compat_diamond": 0.85,
        "barber_notes": "Long layers from chin downward. Razor-texturize ends. Trim every 8 weeks.",
        "top_length_cm": 22.0,
        "preview_s3_key": "male/long-and-layered.jpeg",
    },
    {
        "name": "Long Slicked-Back Hair",
        "slug": "long-slicked-back-hair",
        "gender": "male", "texture": "straight", "length": "long", "maintenance": "high",
        "compat_oval": 0.90, "compat_round": 0.62, "compat_square": 0.70,
        "compat_heart": 0.80, "compat_oblong": 0.92, "compat_diamond": 0.85,
        "barber_notes": "Grow past shoulders. Blow dry backward. Shine serum, slick back with comb.",
        "top_length_cm": 25.0,
        "preview_s3_key": "male/long-slicked-back-hair.jpeg",
    },
    {
        "name": "The Bro Flow",
        "slug": "the-bro-flow",
        "gender": "male", "texture": "wavy", "length": "long", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.65, "compat_square": 0.70,
        "compat_heart": 0.82, "compat_oblong": 0.92, "compat_diamond": 0.85,
        "barber_notes": "Let it grow naturally to collar or beyond. Trim split ends. Sea-salt spray.",
        "top_length_cm": 20.0,
        "preview_s3_key": "male/the-bro-flow.jpeg",
    },
    {
        "name": "Low Fade with Sideburns",
        "slug": "low-fade-with-sideburns",
        "gender": "male", "texture": "straight", "length": "medium", "maintenance": "medium",
        "compat_oval": 0.88, "compat_round": 0.80, "compat_square": 0.82,
        "compat_heart": 0.72, "compat_oblong": 0.70, "compat_diamond": 0.75,
        "barber_notes": "Low fade behind ear. Retain full sideburns blended into beard. 6 cm top.",
        "barber_guard": "#1–#2 low fade",
        "top_length_cm": 6.0,
        "preview_s3_key": "male/low-fade-with-sideburns.jpeg",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # FEMALE — short
    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Undercut Bob",
        "slug": "undercut-bob",
        "gender": "female", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.72, "compat_square": 0.78,
        "compat_heart": 0.88, "compat_oblong": 0.85, "compat_diamond": 0.88,
        "barber_notes": "Shaved or very short nape, blunt bob at jaw. Point-cut ends for softness.",
        "top_length_cm": 10.0,
        "preview_s3_key": "female/undercut-bob.jpg",
    },
    {
        "name": "Asymmetrical Bob",
        "slug": "asymmetrical-bob",
        "gender": "female", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.92, "compat_round": 0.78, "compat_square": 0.75,
        "compat_heart": 0.88, "compat_oblong": 0.85, "compat_diamond": 0.82,
        "barber_notes": "One side shorter than the other by 2–3 cm. Point-cut to blend. Flat-iron for sleekness.",
        "top_length_cm": 10.0,
        "preview_s3_key": "female/asymmetrical-bob.jpg",
    },
    {
        "name": "Curly Bob",
        "slug": "curly-bob",
        "gender": "female", "texture": "curly", "length": "short", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.78, "compat_square": 0.72,
        "compat_heart": 0.85, "compat_oblong": 0.82, "compat_diamond": 0.80,
        "bonus_curly_hair": 0.2,
        "barber_notes": "Dry DevaCut at chin length. Diffuse with curl cream. Shape curls at front.",
        "top_length_cm": 10.0,
        "preview_s3_key": "female/curly-bob.jpg",
    },
    {
        "name": "Modern Pixie",
        "slug": "modern-pixie",
        "gender": "female", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.95, "compat_round": 0.70, "compat_square": 0.68,
        "compat_heart": 0.90, "compat_oblong": 0.78, "compat_diamond": 0.88,
        "barber_notes": "Taper nape and sides. Top 5 cm with texture. Side-swept fringe optional.",
        "top_length_cm": 5.0,
        "preview_s3_key": "female/modern-pixie.jpg",
    },
    {
        "name": "Textured Pixie",
        "slug": "textured-pixie",
        "gender": "female", "texture": "wavy", "length": "short", "maintenance": "medium",
        "compat_oval": 0.92, "compat_round": 0.70, "compat_square": 0.68,
        "compat_heart": 0.88, "compat_oblong": 0.78, "compat_diamond": 0.85,
        "barber_notes": "Piece-y textured top 5–6 cm. Taper nape. Matte wax to separate pieces.",
        "top_length_cm": 5.5,
        "preview_s3_key": "female/textured-pixie.jpg",
    },
    {
        "name": "Contemporary Crop",
        "slug": "contemporary-crop",
        "gender": "female", "texture": "straight", "length": "short", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.75, "compat_square": 0.72,
        "compat_heart": 0.85, "compat_oblong": 0.78, "compat_diamond": 0.82,
        "barber_notes": "Short all-over cut 3–4 cm. Scissor-finished. Soft taper at neck.",
        "top_length_cm": 4.0,
        "preview_s3_key": "female/contemporary-crop.jpg",
    },
    {
        "name": "Sleek Undercut Pixie",
        "slug": "sleek-undercut-pixie",
        "gender": "female", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.70, "compat_square": 0.75,
        "compat_heart": 0.85, "compat_oblong": 0.82, "compat_diamond": 0.88,
        "barber_notes": "Undercut nape, longer top 6 cm slicked flat. Gel or serum for sleekness.",
        "top_length_cm": 6.0,
        "preview_s3_key": "female/sleek-undercut-pixie.jpg",
    },
    {
        "name": "Graduated Bob",
        "slug": "graduated-bob",
        "gender": "female", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.88, "compat_round": 0.80, "compat_square": 0.72,
        "compat_heart": 0.82, "compat_oblong": 0.85, "compat_diamond": 0.80,
        "barber_notes": "Stacked nape, graduated to longer at front. Blow dry round-brush for shape.",
        "top_length_cm": 11.0,
        "preview_s3_key": "female/graduated-bob.jpg",
    },
    {
        "name": "Short Shag",
        "slug": "short-shag",
        "gender": "female", "texture": "wavy", "length": "short", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.75, "compat_square": 0.70,
        "compat_heart": 0.85, "compat_oblong": 0.82, "compat_diamond": 0.85,
        "bonus_fine_hair": 0.15,
        "barber_notes": "Layered shag chin-length. Curtain bangs. Razor-edge for lived-in feel.",
        "top_length_cm": 10.0,
        "preview_s3_key": "female/short-shag.jpg",
    },
    {
        "name": "Modern Bowl Cut",
        "slug": "modern-bowl-cut",
        "gender": "female", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.85, "compat_round": 0.82, "compat_square": 0.78,
        "compat_heart": 0.75, "compat_oblong": 0.82, "compat_diamond": 0.78,
        "barber_notes": "Blunt line across forehead and ears. Tapered or undercut nape. Flat-iron for polish.",
        "top_length_cm": 8.0,
        "preview_s3_key": "female/modern-bowl-cut.jpg",
    },
    {
        "name": "Sharp Bob",
        "slug": "sharp-bob",
        "gender": "female", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.88, "compat_round": 0.70, "compat_square": 0.82,
        "compat_heart": 0.78, "compat_oblong": 0.85, "compat_diamond": 0.80,
        "barber_notes": "Blunt jaw-length cut, no layers. Flat-iron for clean lines. Gloss serum.",
        "top_length_cm": 10.0,
        "preview_s3_key": "female/sharp-bob.jpg",
    },
    {
        "name": "Neck-Length Bob",
        "slug": "neck-length-bob",
        "gender": "female", "texture": "straight", "length": "short", "maintenance": "medium",
        "compat_oval": 0.90, "compat_round": 0.82, "compat_square": 0.75,
        "compat_heart": 0.85, "compat_oblong": 0.88, "compat_diamond": 0.82,
        "barber_notes": "Bob at neck, soft layers or blunt. Optional fringe. Blow dry for fullness.",
        "top_length_cm": 9.0,
        "preview_s3_key": "female/neck-length-bob.jpg",
    },
    # ─────────────────────────────────────────────────────────────────────────
    # FEMALE — medium
    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Layered Shoulder-Length Cut",
        "slug": "layered-shoulder-cut",
        "gender": "female", "texture": "wavy", "length": "medium", "maintenance": "low",
        "compat_oval": 0.92, "compat_round": 0.72, "compat_square": 0.78,
        "compat_heart": 0.85, "compat_oblong": 0.90, "compat_diamond": 0.88,
        "barber_notes": "Long layers from chin down. Face-framing pieces. Blow dry or air dry.",
        "top_length_cm": 15.0,
        "preview_s3_key": "female/layered-shoulder-cut.jpg",
    },
    {
        "name": "Modern Shag",
        "slug": "modern-shag",
        "gender": "female", "texture": "wavy", "length": "medium", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.75, "compat_square": 0.72,
        "compat_heart": 0.88, "compat_oblong": 0.88, "compat_diamond": 0.85,
        "bonus_fine_hair": 0.15,
        "barber_notes": "Heavy layers, curtain bangs. Razor-cut ends. Diffuse or air-dry.",
        "top_length_cm": 14.0,
        "preview_s3_key": "female/modern-shag.jpg",
    },
    {
        "name": "Layered Lob",
        "slug": "layered-lob",
        "gender": "female", "texture": "straight", "length": "medium", "maintenance": "low",
        "compat_oval": 0.92, "compat_round": 0.78, "compat_square": 0.80,
        "compat_heart": 0.88, "compat_oblong": 0.88, "compat_diamond": 0.90,
        "barber_notes": "Collarbone-length, long layers, face-framing. Point-cut ends. Round-brush blow dry.",
        "top_length_cm": 14.0,
        "preview_s3_key": "female/layered-lob.jpg",
    },
    {
        "name": "Shoulder-Length Shag",
        "slug": "shoulder-length-shag",
        "gender": "female", "texture": "wavy", "length": "medium", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.72, "compat_square": 0.70,
        "compat_heart": 0.85, "compat_oblong": 0.90, "compat_diamond": 0.85,
        "bonus_fine_hair": 0.15,
        "barber_notes": "Shoulder-length layers with curtain bangs. Sea-salt spray for texture.",
        "top_length_cm": 15.0,
        "preview_s3_key": "female/shoulder-length-shag.jpg",
    },
    {
        "name": "Textured Medium Cut",
        "slug": "textured-medium-cut",
        "gender": "female", "texture": "wavy", "length": "medium", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.75, "compat_square": 0.72,
        "compat_heart": 0.82, "compat_oblong": 0.88, "compat_diamond": 0.85,
        "barber_notes": "Mid-length with light layers. Thinning shears for texture. Mousse + diffuse.",
        "top_length_cm": 14.0,
        "preview_s3_key": "female/textured-medium-cut.jpg",
    },
    {
        "name": "Blunt Mid-Length Cut",
        "slug": "blunt-mid-length-cut",
        "gender": "female", "texture": "straight", "length": "medium", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.68, "compat_square": 0.75,
        "compat_heart": 0.78, "compat_oblong": 0.88, "compat_diamond": 0.82,
        "barber_notes": "One-length blunt cut at collarbone. Flat-iron for glass finish. Gloss serum.",
        "top_length_cm": 14.0,
        "preview_s3_key": "female/blunt-mid-length-cut.jpg",
    },
    {
        "name": "Collarbone Cut",
        "slug": "collarbone-cut",
        "gender": "female", "texture": "straight", "length": "medium", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.72, "compat_square": 0.75,
        "compat_heart": 0.82, "compat_oblong": 0.88, "compat_diamond": 0.85,
        "barber_notes": "Cut precisely at collarbone. Optional face-framing. Blow-dry with paddle brush.",
        "top_length_cm": 15.0,
        "preview_s3_key": "female/collarbone-cut.jpg",
    },
    {
        "name": "Feathered Haircut",
        "slug": "feathered-haircut",
        "gender": "female", "texture": "wavy", "length": "medium", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.72, "compat_square": 0.75,
        "compat_heart": 0.85, "compat_oblong": 0.88, "compat_diamond": 0.85,
        "barber_notes": "Razor-feathered layers throughout. Blow dry outward on round brush for lift.",
        "top_length_cm": 14.0,
        "preview_s3_key": "female/feathered-haircut.jpg",
    },
    # ─────────────────────────────────────────────────────────────────────────
    # FEMALE — long
    # ─────────────────────────────────────────────────────────────────────────
    {
        "name": "Layered Long Cut",
        "slug": "layered-long-cut",
        "gender": "female", "texture": "straight", "length": "long", "maintenance": "low",
        "compat_oval": 0.92, "compat_round": 0.68, "compat_square": 0.72,
        "compat_heart": 0.85, "compat_oblong": 0.90, "compat_diamond": 0.88,
        "barber_notes": "Long layers starting below chin. Face-framing. Trim split ends every 10 weeks.",
        "top_length_cm": 28.0,
        "preview_s3_key": "female/layered-long-cut.jpg",
    },
    {
        "name": "Cascading Waves",
        "slug": "cascading-waves",
        "gender": "female", "texture": "wavy", "length": "long", "maintenance": "low",
        "compat_oval": 0.90, "compat_round": 0.65, "compat_square": 0.70,
        "compat_heart": 0.85, "compat_oblong": 0.92, "compat_diamond": 0.88,
        "bonus_fine_hair": 0.1,
        "barber_notes": "Long invisible layers. Let waves fall freely. Sea-salt spray or curl cream.",
        "top_length_cm": 30.0,
        "preview_s3_key": "female/cascading-waves.jpg",
    },
    {
        "name": "Long Cut with Face-Framing Layers",
        "slug": "long-face-framing-cut",
        "gender": "female", "texture": "straight", "length": "long", "maintenance": "medium",
        "compat_oval": 0.95, "compat_round": 0.70, "compat_square": 0.75,
        "compat_heart": 0.90, "compat_oblong": 0.88, "compat_diamond": 0.90,
        "barber_notes": "Long one-length base with face-framing layers from cheekbone down. Light gloss.",
        "top_length_cm": 28.0,
        "preview_s3_key": "female/long-face-framing-cut.jpg",
    },
    {
        "name": "Blunt Long Cut",
        "slug": "blunt-long-cut",
        "gender": "female", "texture": "straight", "length": "long", "maintenance": "low",
        "compat_oval": 0.88, "compat_round": 0.65, "compat_square": 0.72,
        "compat_heart": 0.78, "compat_oblong": 0.90, "compat_diamond": 0.82,
        "barber_notes": "One-length blunt cut mid-back. No layers. Flat-iron + shine spray for impact.",
        "top_length_cm": 30.0,
        "preview_s3_key": "female/blunt-long-cut.jpg",
    },
]

assert len(CATALOG) == 66, f"Expected 66 catalog entries, got {len(CATALOG)}"


async def seed() -> None:
    from sqlalchemy import func as sqlfunc

    async with AsyncSessionFactory() as session:
        result = await session.execute(
            select(sqlfunc.count()).select_from(HairstyleCatalog)
        )
        current_count = result.scalar()

        if current_count == len(CATALOG):
            print(f"Catalog already has {current_count} entries — skipping.")
            return

        if current_count > 0:
            print(f"Replacing {current_count} existing entries with {len(CATALOG)} new ones...")
            await session.execute(delete(HairstyleCatalog))

        for entry in CATALOG:
            session.add(HairstyleCatalog(id=uuid.uuid4(), **entry))

        await session.commit()
        print(f"Seeded {len(CATALOG)} hairstyle catalog entries.")


if __name__ == "__main__":
    asyncio.run(seed())
